### ISSUE TITLE
Add support for CLI

### ISSUE THREAD

**Issue by vittee** [priesdelly/WinSSHCopyId#1]
This should be useful when using in a CLI environment

**Comment by priesdelly** [comment]
Ok I will keep it on my to-do list

**Comment by priesdelly** [comment]
The feature has been added in #2. The user documentation will follow shortly.

**Comment by priesdelly** [comment]
Already updated user documentation: https://github.com/priesdelly/WinSSHCopyId/commit/43ca7b5b3811195405d7483ff2ca0daa5f92d043

**Comment by priesdelly** [comment]
Already updated user documentation: https://github.com/priesdelly/WinSSHCopyId/commit/e22d757c66ffe0b180c2699d7b62ca13a91ae1a3
